<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Portal')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
        <script>
            const ajaxUrl = '<?= $this->serverUrl('/SetWord');?>';
        </script>
    </head>
    <body class="body_container <?= $this->translate('ltr');?>">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Portal\Module::VERSION ?>"/>&nbsp;Demo Avi Project
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>"> <?= $this->translate('Home');?><span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"><?= $this->translate('language');?><b class="caret"></b></a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="?lang=en_US"><?= $this->translate('English');?></a></li>
                                <li><a class="dropdown-item" href="?lang=he_IL"><?= $this->translate('Hebrew');?></a></li>
                                <li><a class="dropdown-item" href="?lang=ru_RU"><?= $this->translate('Russian');?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> <?= $this->translate('by Zend Technologies Ltd. All rights reserved.');?></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
        <?= $this->inlineScript()->prependFile($this->basePath('js/app.js'))
        ?>
    </body>
</html>
